package main

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"os"
	"time"

	"github.com/go-pdf/fpdf"
)

func generatePDF(sess *Session) ([]byte, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetAutoPageBreak(true, 20)
	pdf.AddPage()

	// Header bar
	pdf.SetFillColor(67, 56, 202) // indigo-700
	pdf.Rect(0, 0, 210, 35, "F")
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 20)
	pdf.SetXY(15, 10)
	pdf.Cell(0, 10, "Testa Edu")
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetXY(15, 20)
	pdf.Cell(0, 8, "Education Credential Issuance Portal")

	// Title
	pdf.SetTextColor(31, 41, 55)
	pdf.SetFont("Helvetica", "B", 16)
	pdf.SetXY(15, 45)
	pdf.Cell(0, 10, "Verifiable Education Credential")

	// Credential details
	pdf.SetFont("Helvetica", "", 10)
	y := 60.0

	fields := []struct {
		Label string
		Value string
	}{
		{"Student Name", sess.Form.StudentName},
		{"Institution", sess.Form.Institution},
		{"Degree", sess.Form.Degree},
		{"Field of Study", sess.Form.FieldOfStudy},
		{"Enrollment Date", sess.Form.EnrollmentDate},
		{"Graduation Date", sess.Form.GraduationDate},
		{"Student ID", sess.Form.StudentID},
		{"GPA", sess.Form.GPA},
		{"Honors", sess.Form.Honors},
	}

	for _, f := range fields {
		if f.Value == "" {
			continue
		}
		pdf.SetFont("Helvetica", "B", 10)
		pdf.SetXY(15, y)
		pdf.Cell(50, 7, f.Label+":")
		pdf.SetFont("Helvetica", "", 10)
		pdf.SetXY(65, y)
		pdf.Cell(0, 7, f.Value)
		y += 8
	}

	// Issuer DID
	y += 4
	pdf.SetDrawColor(200, 200, 200)
	pdf.Line(15, y, 195, y)
	y += 4
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetXY(15, y)
	pdf.Cell(50, 6, "Issuer DID:")
	pdf.SetFont("Courier", "", 7)
	pdf.SetXY(65, y)
	pdf.Cell(0, 6, config.IssuerDID)
	y += 8

	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetXY(15, y)
	pdf.Cell(50, 6, "Issued:")
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetXY(65, y)
	pdf.Cell(0, 6, time.Now().UTC().Format("2006-01-02 15:04 UTC"))
	y += 8

	if sess.Verified {
		pdf.SetFont("Helvetica", "B", 9)
		pdf.SetXY(15, y)
		pdf.Cell(50, 6, "Verification:")
		pdf.SetTextColor(5, 150, 105)
		pdf.SetFont("Helvetica", "B", 9)
		pdf.SetXY(65, y)
		pdf.Cell(0, 6, "PASSED")
		pdf.SetTextColor(31, 41, 55)
		y += 8
	}

	// QR Code
	if sess.QR != nil && sess.QR.QRPngBase64 != "" {
		y += 6
		pdf.SetDrawColor(200, 200, 200)
		pdf.Line(15, y, 195, y)
		y += 6

		pdf.SetFont("Helvetica", "B", 12)
		pdf.SetXY(15, y)
		pdf.Cell(0, 8, "Verification QR Code")
		y += 12

		// Decode base64 PNG and register as image
		pngData, err := base64.StdEncoding.DecodeString(sess.QR.QRPngBase64)
		if err == nil {
			tmpFile, err := os.CreateTemp("", "qr-*.png")
			if err == nil {
				tmpFile.Write(pngData)
				tmpFile.Close()
				defer os.Remove(tmpFile.Name())

				pdf.Image(tmpFile.Name(), 60, y, 90, 90, false, "PNG", 0, "")
				y += 94

				pdf.SetFont("Helvetica", "", 8)
				pdf.SetTextColor(107, 114, 128)
				centerX := 105.0
				pdf.SetXY(centerX-30, y)
				pdf.CellFormat(60, 6, "Scan with Inji Verify", "", 0, "C", false, 0, "")
				pdf.SetTextColor(31, 41, 55)
			}
		}
	}

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "", 7)
	pdf.SetTextColor(156, 163, 175)
	pdf.CellFormat(0, 10,
		fmt.Sprintf("Generated by Testa Edu Credential Issuance Portal | Powered by CREDEBL | %s",
			time.Now().UTC().Format("2006-01-02")),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("generating PDF: %w", err)
	}
	return buf.Bytes(), nil
}
